apiVersion: v1
kind: Service
metadata:
  name: object-storage-manager-stage-service
  labels:
    app: object-storage-manager-stage
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.116
  externalIPs:
  - 10.24.24.116
  ports:
  - name: http
    port: 82 #local out port
    protocol: TCP
    targetPort: 82 # container port
  selector:
    app: object-storage-manager-stage #find all pod with app name
  sessionAffinity: None
